// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUG7KNaB_RIhql6UlLkpOxXG73ugCB3wM',
    appId: '1:393567676133:web:fe7fd7a8a8e010fac4d60c',
    messagingSenderId: '393567676133',
    projectId: 'projeto-para-flutter-com-api',
    authDomain: 'projeto-para-flutter-com-api.firebaseapp.com',
    storageBucket: 'projeto-para-flutter-com-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3fCITJgI-iERg8V6cvb4bwRAo1w27dW0',
    appId: '1:393567676133:android:bb75da6f11109213c4d60c',
    messagingSenderId: '393567676133',
    projectId: 'projeto-para-flutter-com-api',
    storageBucket: 'projeto-para-flutter-com-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsa6uI1jEORLlGPaal4swttIkb80CO1xI',
    appId: '1:393567676133:ios:a94791e59d06a021c4d60c',
    messagingSenderId: '393567676133',
    projectId: 'projeto-para-flutter-com-api',
    storageBucket: 'projeto-para-flutter-com-api.appspot.com',
    iosClientId: '393567676133-lg2jipo3prll2blomg91pldpr37lolih.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsa6uI1jEORLlGPaal4swttIkb80CO1xI',
    appId: '1:393567676133:ios:a94791e59d06a021c4d60c',
    messagingSenderId: '393567676133',
    projectId: 'projeto-para-flutter-com-api',
    storageBucket: 'projeto-para-flutter-com-api.appspot.com',
    iosClientId: '393567676133-lg2jipo3prll2blomg91pldpr37lolih.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercam',
  );
}
